remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

title: "전국 도·시·군·구 지자체 홈페이지 바로가기"
description: "전국 도·시·군·구 지자체 홈페이지 바로가기"

url: "https://lgov.virz.net"

header_pages:
  - index.md
  - about.md
